logging:
  formatters:
    brief:
      format: '%(message)s'
    default:
      format: '%(asctime)s :: %(name)s:%(levelname)s :: %(module)s:%(funcName)s:%(lineno)d
        :: %(message)s'
  handlers:
    console:
      class: logging.StreamHandler
      formatter: default
      stream: ext://sys.stdout
    file:
      backupCount: 3
      class: logging.handlers.RotatingFileHandler
      filename: app.log
      formatter: default
      maxBytes: 1024
  loggers:
    ? ''
    : handlers:
      - console
      level: INFO
    test:
      handlers:
      - console
      level: DEBUG
  version: 1
